export const AUTH_ROUTE = '/auth'
export const REGISTRATION_ROUTE = '/registration'
export const CHATS_ROUTE = '/chats'
export const ERROR_ROUTE = '/error'
export const CHATIDPAGE_ROUTE = '/chats/:id'